version: '3'

volumes:
  kittygram_pg_data:
  kittygram_static:
  kittygram_media:

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - kittygram_pg_data:/var/lib/postgresql/data

  backend:
    image: qsms78/kittygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - kittygram_static:/backend_static
      - kittygram_media:/media

  frontend:
    image: qsms78/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - kittygram_static:/frontend_static

  gateway:
    image: qsms78/kittygram_gateway
    env_file: .env
    depends_on:
      - backend
    ports:
      - '9000:80'
    volumes:
      - kittygram_static:/kittygram_staticfiles
      - kittygram_media:/media
